### ISSUE TITLE
Transparent background for VisitableView

### ISSUE THREAD

**Issue by pfeiffer** [software-mansion-labs/react-native-turbo-demo#10]
Today the `VisitableView` is opaque with a white background. It would be great if the view background was instead transparent unless explicitly set eg. via `styles={{ backgroundColor: .. }}`.

Having a transparent background would allow a VisitableView be shown as a screen with `presentation: transparentModal`, covering the screen, but allowing the content behind to be shown and the `<body>` of the web page to control the transparency, eg:

```html
<html>
  <style>
    body {
      background: rgba(#000, 0.3);
      color: #fff;
      display: flex;
      align-items: center;
      justify-content: center;
    }
  </style>
  <body>
    <h1>Full page with semi-transparent background</h1>
  </body>
</html>
```

<img width="318" alt="image" src="https://user-images.githubusercontent.com/195925/185154559-1e5ec75a-70cf-436b-8e49-1697f208562d.png">

The functionality would allow showing webpages that blend in with the content behind it - for instance dialogs.

**Comment by pklatka** [comment]
You can take a different approach to handle dialogs, don't see any benefits of doing that for now. For example you can use `FullWindowOverlay` from [react-native-screens](https://github.com/software-mansion/react-native-screens).
