### ISSUE TITLE
Strada not working on Android

### ISSUE THREAD

**Issue by cspeer** [software-mansion-labs/react-native-turbo-demo#141]
Hi again,

I've noticed that none of my strada components appear to be working when I'm on Android.
So I dug around a little and found out that when Strada Web [sends the message on Android](https://github.com/hotwired/strada-web/blob/main/src/bridge.js#L40) this exception is returned:
```
Error: Java exception was raised during method invocation
```
I have no more info than that unfortunately. Nothing's showing in the expo log.

Have you run into this before? Is there something I can do? It's working perfectly fine on iOS.

Thanks!

**Comment by cspeer** [comment]
So, I dug a little deeper, and it turns out that this exception is only thrown if the payload that's sent along from the js bridge component contains a non-empty array. Something like:

```js
import { BridgeComponent } from '@hotwired/strada';

export default class extends BridgeComponent {
  static component = 'app';

  connect () {
    this.send('connect', { value1: 'strings are fine', value2: [1, 2, 3] }, () => null);
  }
}
```

**Comment by pklatka** [comment]
Hi @cspeer,

thank you for reporting the issue. I've created an `update-server` branch that includes your BridgeComponent example (I modified `form_controller.js` to send the same payload). Unfortunately, I cannot reproduce the error. Without a more detailed error message or example, I am unable to resolve the issue. Are you able to provide example app/website or, the best option, modify example app/server in the repo which would make the app to crash?

**Comment by pklatka** [comment]
@cspeer does this issue still occurs when using beta versions ([react-native-web-screen@1.0.0-beta.3](https://github.com/software-mansion-labs/react-native-turbo-demo/releases/tag/react-native-web-screen%401.0.0-beta.3) and [react-native-turbo@1.0.0-beta.1](https://github.com/software-mansion-labs/react-native-turbo-demo/releases/tag/react-native-turbo%401.0.0-beta.1))?

**Comment by cspeer** [comment]
Hi @pklatka,

sorry for the late reply.
I just created a new expo dev build with both of these releases, but unfortunately the problem still persists.
I wish I had better news.
