### ISSUE TITLE
Trouble getting example app started

### ISSUE THREAD

**Issue by iseth** [software-mansion-labs/react-native-turbo-demo#164]
### Description

Seems like since the big commit: #143 there is an issue getting the example demo app started.
Cannot read property 'getSessionHandles' of null, js engine: hermes

I have done quite a bit trying to figure what is going on so i thought maybe someone can point me in the right direction.

### Steps to reproduce

1. clone repo,
2. yarn install
3. yarn dev
4. Fails

### Snack or a link to a repository

https://github.com/software-mansion-labs/react-native-turbo-demo

### React Native Turbo version

50.0.1

### React Native version

0.73.4

### Platforms

iOS

### JavaScript runtime

Hermes

### Workflow

None

### Architecture

None

### Build type

None

### Device

None

**Comment by iseth** [comment]
Would love to help with documentation to describe how to get this up and running nicely.

**Comment by pklatka** [comment]
Hi, I've merged #163, it should resolve the issue.

**Comment by pklatka** [comment]
Tested that few minutes ago, it's working properly. If you still have some issues make sure that you have pulled recent changes and run `yarn clean && yarn && yarn dev:ios` in the root directory. See [CONTRIBUTING.md](https://github.com/software-mansion-labs/react-native-turbo-demo/blob/main/CONTRIBUTING.md).
