### ISSUE TITLE
Plan to integrate with expo go

### ISSUE THREAD

**Issue by iseth** [software-mansion-labs/react-native-turbo-demo#191]
I am new to this library but i was wondering is there anyway to use this with the expo go app so I can develop and test it on a device through the expo go app?

**Comment by PedroAugustoRamalhoDuarte** [comment]
Hello @iseth, for now we cannot use `react-native-turbo` with managed expo due to native code linking without development builds: https://docs.expo.dev/workflow/customizing/.

But we can use `react-native-web-screen` package to enhance the normal webview for react native
