### ISSUE TITLE
Could not read script '...\node_modules\react-native-turbo\android\turbo-android-dependencies.gradle' as it does not exist.

### ISSUE THREAD

**Issue by Quent1Pr** [software-mansion-labs/react-native-turbo-demo#207]
### Description

Hello,
I'm on Windows 11 with this Android Studio version : 
Android Studio Jellyfish | 2023.3.1
Build #AI-233.14808.21.2331.11709847, built on April 12, 2024
Runtime version: 17.0.10+0--11572160 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 11.0
GC: G1 Young Generation, G1 Old Generation

I have this error  when I use the command "yarn dev:android" : 
Could not read script '...\node_modules\react-native-turbo\android\turbo-android-dependencies.gradle' as it does not exist.

I have also this warning : 
Warning: SDK processing. This version only understands SDK XML versions up to 3 but an SDK XML file of version 4 was encountered. This can happen if you use versions of Android Studio and the command-line tools that were released at different times.

### Steps to reproduce

1. Git clone
2. yarn install
4. yarn dev:android

### Snack or a link to a repository

https://github.com/software-mansion-labs/react-native-turbo-demo/

### React Native Turbo version

1.0.0

### React Native version

0.73.6

### Platforms

Android

### JavaScript runtime

None

### Workflow

None

### Architecture

None

### Build type

None

### Device

None

**Comment by Quent1Pr** [comment]
Works on ubuntu

**Comment by nebiyuelias1** [comment]
I'm also facing similar issue on windows, does this mean it doesn't work on Windows?
