### ISSUE TITLE
Suggestion : guide to create APK/IPA

### ISSUE THREAD

**Issue by Quent1Pr** [software-mansion-labs/react-native-turbo-demo#211]
Hello,
I think it would be nice to have a small guide to build APK/IPA file.
I'm new on theses dev environments and even with the existing scripts, it's not very intuitive (without mentioning the versions compatibility resolution with all the tech stack).

I think gradle files and version are old on this project. I can't make ./gradlew assembleRelease works

**Comment by pfeiffer** [comment]
Hi! Generating APK/IPA files for distribution is out of scope for this library.

I recommend that you look into [Expo](https://docs.expo.dev/) if you're just getting started with React Native, which has extensive docs and many tutorials online.. This library is compatible with Expo.

**Comment by Quent1Pr** [comment]
Thank you for your reply. I can't make "eas build --platform android --local" works either with the initial state of repository. eas.json in examples/turbo-demo-example seems outdated as eas CLI returns it's not valid.

Readme mentions "How to use" and that works but doesn't mention how to make the first build. I think that would be appreciated for new comers.
Is building with Expo a mandatory ? Does the demo build have been tested with a specific version ?

**Comment by Quent1Pr** [comment]
I start an app from scratch with React Native guide and use react-native-turbo as a dependency.
I meet this error during the build : 

`Could not resolve all task dependencies for configuration ':app:debugRuntimeClasspath'. > Could not find dev.hotwire:turbo:local. Searched in the following locations: - https://oss.sonatype.org/content/repositories/snapshots/dev/hotwire/turbo/local/turbo-local.pom - https://repo.maven.apache.org/maven2/dev/hotwire/turbo/local/turbo-local.pom - file:/home/quentin/RNFinal/cleanrn/AwesomeProject/node_modules/jsc-android/dist/dev/hotwire/turbo/local/turbo-local.pom - https://dl.google.com/dl/android/maven2/dev/hotwire/turbo/local/turbo-local.pom - https://www.jitpack.io/dev/hotwire/turbo/local/turbo-local.pom
Required by: project :app > project :react-native-turbo`

dev.hotwire:turbo:local is referenced in the gradle.build of the package react-native-turbo

**Comment by Quent1Pr** [comment]
Thank you for your reply.
