### ISSUE TITLE
✍️ Refactor package name to react-native-turbo

### ISSUE THREAD

**Issue by keithrfung** [software-mansion-labs/react-native-turbo-demo#29]
I noticed that you had pushed to:
https://www.npmjs.com/package/react-native-turbo

With the package updating, to `react-native-turbo`, there are a couple lines that should be updated as well. Basically playing replace with `react-native-turbo-webview`. Perhaps the repo name should adjust too.

Such as the package.json's
https://github.com/software-mansion-labs/react-native-turbo-demo/blob/ad2aabd20870f2c2470266d979218ae00497653f/package.json#L2

https://github.com/software-mansion-labs/react-native-turbo-demo/blob/3cb7a3d01c57bcb46cdbecfccb3a263bc27444e0/packages/core/package.json#L2

And README
https://github.com/software-mansion-labs/react-native-turbo-demo/blob/ad2aabd20870f2c2470266d979218ae00497653f/README.md?plain=1#L8

**Comment by redbar0n** [comment]
and remove `-demo` from the repo name itself.

**Comment by Fryzu** [comment]
Hi guys 👋🏻 thanks for letting me know. I didn't change the name in the package json as this repository is a monorepo containing two libraries `react-native-turbo` and `react-native-web-screen` (main library is an abstraction layer using `react-navigation` and under the hood using the second library ->`react-native-turbo`) I was going to change the naming anyway in the PR #33. Anyways, good catch @keithrfung 💪🏻

**Comment by PedroAugustoRamalhoDuarte** [comment]
Hello @Fryzu, I've been contemplating the naming of our monorepo and understand the challenges associated with it. I believe using demo names might not be the most optimal choice as it can make the repository harder to find.

I'm proposing a potential change to the overall monorepo name. Perhaps "react-native-turbo" its fine. To illustrate, Expo follows a similar approach with their monorepo: https://github.com/expo/expo/tree/main/packages/expo.

**Comment by redbar0n** [comment]
NB: "Turbo" confusingly has multiple meanings in a React Native (+ Web) context, so don't confuse [Hotwire's Turbo Native](https://turbo.hotwired.dev/) with React Native's own [Turbo Native Modules](https://reactnative.dev/docs/next/the-new-architecture/pillars-turbomodules) architecture, or the [monorepo](https://monorepo.tools/) build system [Turborepo](https://turborepo.org/) (as used in create-t3-turbo, mentioned later here) or its recent sister project [Turbopack](https://turbo.build/pack), which replaces Webpack as a bundler for the web (relevant to React Native Web projects).

It would be a good idea to at least align the NPM name [react-native-turbo](https://www.npmjs.com/package/react-native-turbo) with the github repo name which is now [react-native-turbo-demo](https://github.com/software-mansion-labs/react-native-turbo-demo).

https://dev.to/this-is-learning/the-different-strategies-to-building-a-cross-platform-app-3p56

[‘Turbo Native’ is already taken, ofc](https://x.com/magnemg/status/1578299943290535939?s=46&t=tYj6dxrnDA8GvBz3qad13A)

**Comment by pfeiffer** [comment]
I think `react-native-turbo` would be a fitting repo name as we are approaching a release-ready candidate for the demo project. When the remaining PRs have been merged and Strada compatibility has been added, the library here should be feature compatible with the native Turbo libraries and the demo app in those.
