### ISSUE TITLE
Passing cookies to the webview

### ISSUE THREAD

**Issue by misterAKl** [software-mansion-labs/react-native-turbo-demo#38]
Is there a way to pass cookies to the webview, I have native login and sign up and I want to pass the token in the cookies to login the user. 

Looking at this there should be some way to pass the cookies to the webview
https://github.com/hotwired/turbo-ios/blob/main/Docs/Authentication.md

**Comment by pklatka** [comment]
Hello, with the new version of the libraries, you can set cookies using the `injectJavaScript` method on the `VisitableView` ref. To set cookies via JavaScript, you can use [document.cookie](https://developer.mozilla.org/en-US/docs/Web/API/Document/cookie). 

Also, as stated in the `turbo-ios` docs, it is not needed to do additional work regarding cookies. You can simply use cookies like in a web browser, just make sure that they are persistent, not session cookies.
