### ISSUE TITLE
Navigation to complex routes

### ISSUE THREAD

**Issue by tellodaniel** [software-mansion-labs/react-native-turbo-demo#40]
I want to create an Stack app that allows me to navigate through an authentication process like

```
import React from 'react';
import {
  NavigationContainer,
  useNavigationContainerRef,
} from '@react-navigation/native';
import {SafeAreaProvider} from 'react-native-safe-area-context';
import {createNativeStackNavigator} from '@react-navigation/native-stack';
import {buildWebScreen} from 'react-native-web-screen';

const Stack = createNativeStackNavigator();

const webScreenConfig = {
  baseURL: 'https://lifi.mx/beta',
  routes: {
    Initial: {
      urlPattern: '',
      title: 'Sign In',
    },
    SignUp: {
      urlPattern: 'register/sign_up',
      title: 'sign up',
    },
    Listing: {
      urlPattern: 'listing',
      title: 'sign up',
    },
    Likes: {
      urlPattern: 'likes',
      title: 'product',
    },
  },
};

const webScreens = buildWebScreen(webScreenConfig);

function App() {
  const navigation = useNavigationContainerRef();

  return (
    <SafeAreaProvider>
      <NavigationContainer linking={webScreens.linking} ref={navigation}>
        <Stack.Navigator>
          <Stack.Screen {...webScreens.screens.Initial} />
          <Stack.Screen {...webScreens.screens.SignUp} />
          <Stack.Screen {...webScreens.screens.Listing} />
          <Stack.Screen {...webScreens.screens.Likes} />
        </Stack.Navigator>
      </NavigationContainer>
    </SafeAreaProvider>
  );
}

export default App;
```

Navigation will be from https://lifi.mx/beta to https://lifi.mx/register/sign_up

But I'm getting the following error:

<img width="376" alt="Screenshot 2023-08-01 at 20 22 52" src="https://github.com/software-mansion-labs/react-native-turbo-demo/assets/8240048/9e08475c-8f29-4684-84c6-72f4f8fe3f14">

This will enable in the future a stack navigation like /listing to /product_PeZNpaW5Tw53XAWv

Does anyone has an example of how to achieve this?

**Comment by tellodaniel** [comment]
What I want to achieve is this navigation from from https://lifi.mx/beta to https://lifi.mx/register/sign_up

https://github.com/software-mansion-labs/react-native-turbo-demo/assets/8240048/400387a3-1760-4615-ae4b-1c9bea87b497

**Comment by pklatka** [comment]
Hi, your `webScreenConfig` is incorrect - the routes should be wrapped with the `screens` key. You can see the correct configuration at https://reactnavigation.org/docs/navigation-container/#linking or in the `examples/turbo-demo-expo-example` app.
