### ISSUE TITLE
modal does not work

### ISSUE THREAD

**Issue by yanovitchsky** [software-mansion-labs/react-native-turbo-demo#46]
hello.
Love the library and the way it looks easy.
The only thing we are noticing is presentation: 'modal' does open a page but a normal screen not in modal.

`[Routes.New]: {
      urlPattern: 'posts/new',
      title: 'A Modal ',
      presentation: 'modal',
    },`

Should we configure it differently for it to work?

Thanks again

**Comment by krschacht** [comment]
@mironiasty This is an issue for me as well. What’s your ETA for the next release?

**Comment by pklatka** [comment]
This should no longer be an issue; please check out new releases and the `examples/turbo-demo-expo-example` app. The `modal` presentation is used there and it works properly.
